title: "Adventures through GSoC 2024"
author: "Luna Morrow"
description: "A blog about my experiences through GSoC 2024 with MDAnalysis, as an aspiring Research Software Engineer."

# Email / Social media user names used by the minima theme:
email: "luna.morrow@gmail.com"
twitter_username: "LunaMorrow22"
github_username: "lunamorrow"
linkedin_username: "luna-morrow-b2b027232"

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
